name: Initial Publish Fed2
on: workflow_dispatch

jobs:
  initial-publish:
    runs-on: ubuntu-latest
    env:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      APOLLO_GRAPH_REF: lenny-scratch-1@current-fed2
    steps:
      - uses: actions/checkout@v2
      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/v0.1.0 | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
      - name: Publish products
        run: |
          rover subgraph publish $APOLLO_GRAPH_REF --schema ./products/schema.graphql --name products --routing-url http://products:4000 --convert
      - name: Publish reviews
        run: |
          rover subgraph publish $APOLLO_GRAPH_REF --schema ./reviews/schema.graphql --name reviews --routing-url http://reviews:4000
