name: Products Publish
on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - "products/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      APOLLO_GRAPH_REF: ${{ secrets.APOLLO_GRAPH_REF }}
      APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/v0.1.0 | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
      - name: Publish products
        run: |
          rover subgraph publish $APOLLO_GRAPH_REF --schema ./products/schema.graphql --name products
      - name: Publish products fed2
        run: |
          rover subgraph publish lenny-scratch-1@current-fed2 --schema ./products/schema.graphql --name products
