name: Reviews Test
on:
  workflow_dispatch: {}
  pull_request:
    branches: [main]
    paths:
      - "reviews/**"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      APOLLO_GRAPH_REF: ${{ secrets.APOLLO_GRAPH_REF }}
      APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/v0.1.0 | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
      - name: Check reviews
        run: |
          rover subgraph check $APOLLO_GRAPH_REF --schema ./reviews/schema.graphql --name reviews
